### ISSUE TITLE
Tracectory Header 

### ISSUE THREAD

**Issue by PDuckworth** [strands-project/trajectory_behaviours#10]
@ferdianjovan Do you know what the information in the Trajectory Header field is? 

sequence_id - what is this?
stamp - is this the time stamp of the original poses, or when the trajectory importer was run?

**Comment by ferdianjovan** [comment]
Sequence_id is the number id for the chunk of trajectory in mini batch mode. So to stitch the chunk of trajectories, you just need to stitch them in the order of sequence_id.
The stamp is the time stamp of the original poses.

**Comment by PDuckworth** [comment]
I don't use sequence_id to stitch the mini-batch trajectories together. I just assume if they have the same uuid, I merge the new one onto the end of the previous one.

**Comment by ferdianjovan** [comment]
that also works. It was intended in the case we want to store mini batch form in database, which is not the case atm.

**Comment by ferdianjovan** [comment]
I want to clear things up, the header from trajectory message is not important as the time in the header refers to the time the message was created not the time of poses (or the first pose). The header in each trajectory (GeometryMessage/PoseStamped) refers to the time from people_tracker (the time stamp of original poses).

Sorry for the confusion.

**Comment by PDuckworth** [comment]
@hawesie / @cdondrup Can either of you close this?

**Comment by cdondrup** [comment]
Can't :(
@hawesie or @marc-hanheide should be able
