### ISSUE TITLE
Stitch together mini-batch trajectories when doing recognition

### ISSUE THREAD

**Issue by hawesie** [strands-project/trajectory_behaviours#5]
The mini-batch trajectories come in non-overlapping chunks. In the recognition node these can be stitched together to make longer trajectories.

(as an aside, maybe @ferdianjovan can just make the mini-batch trajectories extend as more data comes in)

**Comment by PDuckworth** [comment]
@hawesie: @ferdianjovan didn't want to do what you sugest, as the msg might become too large given a stationary person. Do you have an opinion on that?

**Comment by ferdianjovan** [comment]
Yup, that is what I want to avoid. If we include information from human trajectory classifier, we might be able to drop stationary persons from the message.

**Comment by hawesie** [comment]
I meant internally to the recognition node. But if it's a problem there then ignore this.

**Comment by PDuckworth** [comment]
I can hold onto the qsrs for the previous uuid inside the service (if you agree) and check whether it's the same uuid as the current uuid. I should be able to calculate the qsrs for the new batch, and then add them onto the end of the matrix (obj-pairs x qsr per time point). Assuming services can remember things between calls...

**Comment by PDuckworth** [comment]
@ferdianjovan Do the mini-batches of trajectories you publish ever overlap? Because I receive the first mini-batch trajectory as: poses[0] -> poses[n], then the second mini-batch poses[0] -> poses[m]. Can I assume poses[0] in the second mini-batch is timepoint [n+1] ??

**Comment by ferdianjovan** [comment]
Yes, you can

**Comment by PDuckworth** [comment]
@hawesie, @ferdianjovan  This is done. Clone my repo for updated code.

**Comment by hawesie** [comment]
@PDuckworth please can you create a PR to add the updated code to the copy of your repo in the strands-project account. We should start treating that as the master repo, with people forking from that for development.

**Comment by PDuckworth** [comment]
@hawesie Done. 

Let me know if it doesn't work. It should be a stable version.

**Comment by PDuckworth** [comment]
@hawesie can we close this? They are being stitched together after the QSRs are being generated. The Episodes are updated on mongodb if they belong to the same UUID.
